# Generated by Django 3.0.9 on 2020-08-06 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200806_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='button_text_two',
            field=models.CharField(default='Read Blog', help_text='Read Blog', max_length=50),
        ),
    ]
