# Generated by Django 3.0.9 on 2020-08-07 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='section_title',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
